# Generated by Django 4.1 on 2023-06-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_alter_listing_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='bidmodel',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_currentprice', to='auctions.bidmodel'),
        ),
        migrations.AlterField(
            model_name='bidmodel',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
    ]
