# Generated by Django 4.1 on 2023-06-06 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_current_price_bidmodel_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isactive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
