# Generated by Django 4.1 on 2023-06-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_isactive_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmodel',
            name='current_bid',
            field=models.IntegerField(),
        ),
    ]
