# Generated by Django 4.1 on 2023-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
