# Generated by Django 4.1 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
